### ISSUE TITLE
Why is veterans day the only US bank holiday?

### ISSUE THREAD

**Issue by yackSpillsaps** [commenthol/date-holidays#177]
In the entire 21st century, the library reports only 29 US type=bank holidays, and all of them are a Veterans Day that falls on a weekend being observed on a Monday or Friday (a substitute=true day).
 
![Screenshot from 2020-10-13 17-44-43](https://user-images.githubusercontent.com/6422732/96157869-d5f50580-0ee0-11eb-9e7d-901289ee4564.png)

There is both a public weekend day, and a bank substitute day for each:

![Screenshot from 2020-10-13 17-49-49](https://user-images.githubusercontent.com/6422732/96157951-f329d400-0ee0-11eb-902f-88cb4194d956.png)

For all other US public holidays that fall on a weekend the substitute day is also type=public. 

![Screenshot from 2020-10-15 12-10-43](https://user-images.githubusercontent.com/6422732/96158132-2b311700-0ee1-11eb-8dc0-74076ae31be5.png)

I googled some government sites but didn't find anything about Veterans Day being the only US bank holiday.  Actually, I didn't find anything that suggests that the US has official bank holidays at all.

I assume that the Veterans Days being type=bank is a bug.

**Comment by gerryster** [comment]
I am pretty sure that Veteran's Day being a bank holiday is intentional. https://github.com/commenthol/date-holidays/blob/2c462f9a58a585263c6f47a66d7be06fe996b8c0/data/countries/US.yaml#L91 references a source from the Federal Reserve Board of Governors which is pretty authoritative for the US banking system. Note that Veteran's Day is also a federal holiday per https://www.law.cornell.edu/uscode/text/5/6103 (also referenced in US.yaml). On years when Veteran's Day is a weekday, only one holiday is produced which is the public holiday. However, on years when Veteran's Day occurs on a weekend, such as 2023, two holidays are produced. A bank holiday for Friday, November 10, 2023 and a public holiday for Saturday, November 11, 2023, as seen [in the test fixtures](https://github.com/commenthol/date-holidays/blob/2c462f9a58a585263c6f47a66d7be06fe996b8c0/test/fixtures/US-2023.json#L138-L157).

As to your question regarding why there are not more US bank holidays, the only other two federal holidays observed by banks which could fall on a weekend are Independence Day and Christmas. One could argue that these two holidays should be setup similarly to Veteran's Day where a weekday bank holiday is created on the years where they fall on a weekend. However, there are public holiday substitute days already defined on those week days. For example, [2020 Independence Day](https://github.com/commenthol/date-holidays/blob/2c462f9a58a585263c6f47a66d7be06fe996b8c0/test/fixtures/US-2020.json#L92-L110). Since Independence Day and Christmas are more major holidays in the US where most employees would also get a day off on the substitute day, I believe that this is modeled correctly.

Let me know if this rationale makes sense to you.

**Comment by yackSpillsaps** [comment]
@gerryster , Thanks for your thoughtful reply.

 I may have misunderstood, but It seems like the argument for Veterans Day being treated differently then New Year's Day, Independence Day, and Christmas is based on the idea of the latter being "more major holidays". I tend to agree that they are more significant, but I have a feeling that some groups would not ; )

I think it makes more sense to model all federal holidays the same way.  I'm unable to find any legal-ish references that say Veterans Days is different from the others. If it were, I would expect the Cornell Law link you provided above to mention it. Also,  the [Federal Reserve link](https://www.federalreserve.gov/aboutthefed/k8.htm) in [US.yaml](https://github.com/commenthol/date-holidays/blob/9fc2713be6af3f156c727f27f0c33cf8c14828e4/data/countries/US.yaml#L91) doesn't say Veterans Day is special.

But again, I see your point also.
