### ISSUE TITLE
How can I filter / remove some holidays?

### ISSUE THREAD

**Issue by marinabrcls** [commenthol/date-holidays#254]
Hello!

I want to use this library to handle holidays on the front-end of my application, which is React.js. My back-end, though, is in Python, so I'm using a different library to handle holidays in there (workalendar). My problem is that the considered holidays are different in these libraries. My python lib is giving me **12** bank holidays in Brazil in 2021, and that's the amount I want. But here in date-holidays I'm getting **17** dates, so I want to narrow that down. Is there a recommended way to do this? I thought about filtering them by "type", choosing "bank", but in Brazilian holidays we don't have any hoilday listed as "bank type", so it was no help.

(I got these references from https://commenthol.github.io/date-holidays/#pt/2021/BR/--)

Thanks in advance!

**Comment by commenthol** [comment]
Please check the interface description at https://github.com/commenthol/date-holidays-parser/blob/a9b244f1e4a5d6ce89704351f4d172bd17904ed8/types/index.d.ts#L121

Just for being curious: Why do you want to use 2 different holiday libraries? Instead of syncing both of them the one or the other way? Wouldn't it make more sense to check the accuracy and file PRs in one or the other lib to fix things also for others?

**Comment by marinabrcls** [comment]
Hey, thanks again for the reply! It helped me. :)

**Comment by marinabrcls** [comment]
To answer your question: it wasn't really my choice to use both libs, it was required of me by the CTO, for many different reasons. The python lib was already there before. I could have my back-end lib send to the front-end the correct date, but that would take the time of a request and I wanted the date to be shown simultaneously, so that's why I needed another lib in the front-end.

Anyways, thanks for the support! Keep up the good work! <3
