### ISSUE TITLE
isHoliday() returning holidays on wrong days

### ISSUE THREAD

**Issue by kodie** [commenthol/date-holidays#26]
Hey! So I'm a little confused on how to get `isHoliday()` working correctly.

I know that it respects timezones but I'm still having troubles getting it to return the correct days.

Here is the code I have:

```javascript
var Holidays = require('date-holidays')
var hd = new Holidays('US')
console.log(hd.isHoliday(new Date('2018-01-02 00:00:00 GMT+0000')))

// { date: '2018-01-01 00:00:00',
//   start: 2018-01-01T05:00:00.000Z,
//   end: 2018-01-02T05:00:00.000Z,
//   name: 'New Year\'s Day',
//   type: 'public' }
```

And as you can see it returns New Year's Day for January 2nd, however, New Year's Day is actually on January 1st, therefore it should return false.

I'm pretty sure this has something to do with timezones but is there anyway I can get holidays to only return on the actual day that they are on?

**Comment by commenthol** [comment]
All holidays life in their respective timezone. So assume you living in Honolulu and me in London.
You are with the fireworks at UTC "2016-12-31T14:00Z" while I am still preparing for New Years Eve.
While me celebrating New Year UTC "2017-01-01T00:00Z" you are maybe already dreaming of all the awesome things you are planing to do in this year. Your local time is then "2017-01-01 10:00". 

In your case you seam to require only the date and it's start time you can use the `.date` property which gives you the local date of the event. Otherwise you'll need to do a timezone conversion of your local date string, like this:

```js
var Holidays = require('date-holidays')
var moment = require('moment-timezone')

var hd = new Holidays('US', 'HI') // Hawaii
var tz = hd.getTimezones()[0]
console.log(tz) //> Pacific/Honolulu

var localDateStr = '2017-01-01 00:00'
var dateStr = moment.tz(localDateStr, tz).format()

var res = hd.isHoliday(new Date(dateStr))
console.log(res)
//> { date: '2017-01-01 00:00:00',     //< local time string
//>   start: 2017-01-01T10:00:00.000Z,
//>   end: 2017-01-02T10:00:00.000Z,
//>   name: 'New Year\'s Day',
//>   type: 'public' }
```

**Comment by kodie** [comment]
I see. Thank you for the clarification!
